name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    env:
      DOCKER_USERNAME: actdocker123
      DOCKER_TOKEN: dckr_pat_x5iyZMWLcNILRo6BNSNWJdKyC0o

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js and Build
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build

      - name: Log in to Docker Hub
        run: echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # Adjust the path to your Dockerfile
          push: true
          tags: |
            actdocker123/cicdpipeline:react-sample-app
            # your-docker-hub-username/your-image-name:${{ github.sha }}

      - name: Display Success Message
        run: echo "Build and deploy successful!"
# name: Build and Test

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20"

#       - name: Install Dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: Display Success Message
#         run: echo "Build successful!"
