# name: My first workflow

# on: push

# jobs:
#   first_job:
#     runs-on: self-hosted
#     steps:
#       - name: Welcome Message
#         run: echo "My First Github Actions Job. I have created virtual m/c on window"
#       - name: list files
#         run: ls
#       - name: read files
#         run: cat README.md

name: Node.js Build

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16" # Change this to the Node.js version you need

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build # Change this to your build script or command

      - name: Print Success Message
        if: success()
        run: echo "Build successful! 🎉"
