name: CICD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js and Build
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build

      - name: Displaying Build is Success
        run: echo "Build is successful!"

  docker:
    needs: build
    runs-on: self-hosted
    steps:
      # - name: Clean Docker Buildx Cache
      #   run: docker buildx prune --all --force

      # - name: Checkout
      #   uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Adjust the path to your Dockerfile
          push: true
          tags: actdocker123/cicdpipeline:react-app-V1.0${{ github.run_number }}

      - name: Display Docker Push Message
        run: echo "Pushing Docker Image to DockerHub is Successfull!"

  modifygit:
    needs: docker
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: "ShaikhMJAM/gitops-sampleapp"
          token: ${{ secrets.GIT_PASSWORD }}
      - name: modify the image
        run: |
          git config user.email jaid.shaikh@acuteinformatics.in
          git config user.name ShaikhMJAM
          pwd
          cat react-deployment.yaml
          pwd
          sed -i "s+actdocker123/cicdpipeline.*+actdocker123/cicdpipeline:react-app-V1.0${{ github.run_number }}+g" react-deployment.yaml
          cat react-deployment.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}
