# name: My first workflow

# on: push

# jobs:
#   first_job:
#     runs-on: self-hosted
#     steps:
#       - name: Welcome Message
#         run: echo "My First Github Actions Job. I have created virtual m/c on window"
#       - name: list files
#         run: ls
#       - name: read files
#         run: cat README.md

name: Node.js Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Set PowerShell Path
        run: |
          $powershellPath = "${env:SystemRoot}\System32\WindowsPowerShell\v1.0\powershell.exe"
          Write-Host "PowerShell Path: $powershellPath"
          echo "::add-path::$powershellPath"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js from System
        run: |
          npm --version
          node --version

      - name: Install Dependencies
        run: npm install

      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn Install
        run: yarn install

      - name: Build
        run: npm run build

      - name: Print Success Message
        if: success()
        run: echo "Build successful! 🎉"
