name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js and Build
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Adjust the path to your Dockerfile
          push: true
          tags: actdocker123/cicdpipeline:react-sample-app

      - name: Display Success Message
        run: echo "Build and deploy successful!"
# name: Build and Test

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: self-hosted

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "20"

#       - name: Install Dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: Display Success Message
#         run: echo "Build successful!"
